#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require 'json'

class Polyweather
  def initialize(api_key, lat, long)
    @api_key = api_key
    @lat = lat
    @long = long
  end

  def fetch
    url = "https://api.darksky.net/forecast/#{api_key}/#{lat},#{long}"
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)
    @result = JSON.parse(response.body)
  end

  def currently
    # {"time"=>1508405747, "summary"=>"Partly Cloudy", "icon"=>"partly-cloudy-night", "nearestStormDistance"=>299, "nearestStormBearing"=>198, "precipIntensity"=>0, "precipProbability"=>0, "temperature"=>46.06, "apparentTemperature"=>46.06, "dewPoint"=>43.31, "humidity"=>0.9, "pressure"=>1024.91, "windSpeed"=>1.03, "windGust"=>2.32, "windBearing"=>224, "cloudCover"=>0.29, "uvIndex"=>0, "visibility"=>10, "ozone"=>295.22}

    raise RuntimeError("Call fetch before calling currently") if result.nil?
    result["currently"]
  end

  def to_s
    puts "#{icon} #{temperature}\u{00B0}F #{summary}"
    puts icon
  end

  def temperature
    currently["temperature"]
  end

  def summary
    currently["summary"]
  end

  def icon
    case currently["icon"]
    when "clear-day" then "\uf00d"
    when "clear-night" then "\u{f00d}"
    when "rain" then "\u{f019}"
    when "snow" then "\u{f01b}"
    when "sleet" then "\u{f0b5}"
    when "wind" then "\u{f050}"
    when "fog" then "\u{f014}"
    when "cloudy" then "\u{f013}"
    when "partly-cloudy-day" then "\u{f002}"
    when "partly-cloudy-night" then "\u{f086}"
    when "hail" then "\u{f015}"
    when "thunderstorm" then "\u{f01e}"
    when "tornado" then "\u{f056}"
    end
  end

  private

  attr_reader :api_key, :lat, :long, :result
end

p = Polyweather.new("5b6b96cc1b7dbdd2db851d95f8f2d3e9", "40.0756496", "-75.299668")
p.fetch
puts p.to_s
